language: python
python:
  - "3.6"

branches:
  only:
  - master
  - dev

install:
  - "pip install -r requirements.txt"
  - "pip install -r tests/requirements.txt"

script:
  - "export PYTHONPATH=.:vendor"
  - "python -m unittest discover tests"
